name: alfread_demo

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  alfred:
  json_annotation:
  corsac_jwt: ^1.0.0-nullsafety.1
  dbcrypt: ^2.0.0
  get_it: ^7.6.0
  mongo_dart:

dev_dependencies:
  build_runner:
  json_serializable:
  test:
  http: